name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.0]
    steps:
      - uses: actions/checkout@master
      - name: install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Deploy to production
        uses: awb-pw/deploy-to-github-pages-action@1.1.1
        env:
          AUTHOR: Luca-thought
          BUILD_PATH: public
          GITHUB_PAGE_NAME: https://luca-thought.github.io
          PA_TOKEN: fb2c831c9a85d4ef7492f4cab9fef4b0a96bdc53
          USERNAME: Luca-thought
          EMAIL: luca.vescovi88@gmail.com